-- Qualified leads from the chat qualifier
CREATE TABLE IF NOT EXISTS mxdr_leads (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMP DEFAULT NOW(),
    company_name VARCHAR(255),
    industry VARCHAR(100),
    employee_count VARCHAR(50),
    contact_name VARCHAR(255),
    contact_email VARCHAR(255),
    contact_phone VARCHAR(50),
    has_third_party_requirements BOOLEAN DEFAULT FALSE,
    has_compliance_needs BOOLEAN DEFAULT FALSE,
    has_current_security_provider BOOLEAN DEFAULT FALSE,
    has_visibility_gaps BOOLEAN DEFAULT FALSE,
    environment_type VARCHAR(50),
    microsoft_license VARCHAR(50),
    handles_sensitive_data BOOLEAN DEFAULT FALSE,
    pain_points JSONB DEFAULT '[]',
    recommended_solution VARCHAR(100),
    recommended_addons JSONB DEFAULT '[]',
    chat_summary TEXT,
    qualification_score INTEGER DEFAULT 0,
    status VARCHAR(50) DEFAULT 'new',
    assigned_to VARCHAR(100),
    notes TEXT,
    last_contacted_at TIMESTAMP,
    next_followup_at TIMESTAMP,
    followup_count INTEGER DEFAULT 0
);
